name: TaProntos

on:
  push:
    branches: [ "main" ]
    
jobs:  
  Build:
    runs-on: ubuntu-latest
    name: Build 
    steps:
      - name: Fazer o checkout usando action do catálogo do Marketplace
        uses: actions/checkout@v2
      - name: Configurar Node 14 usando action do catálogo do Marketplace
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Mostrar versão do Node que foi configurada
        run: node --version
      - name: Instalar npm
        run: npm install
      - name: Rodar script 'build' se ele existir no package-json
        run: npm run build --if-present

  Deploy-on-Cloud:
    runs-on: ubuntu-latest
    needs: Build
    name: Deploy on Cloud
    steps:
      - name: Fazer o Deploy do código no servidor hospedado em nuvem na plataforma Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}

  Test: 
    runs-on: ubuntu-latest
    needs: Build
    name: Test
    steps:
      - name: Fazer o checkout usando action do catálogo do Marketplace
        uses: actions/checkout@v2
      - name: Configurar Node 14 usando action do catálogo do Marketplace
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Mostrar versão do Node que foi configurada
        run: node --version
      - name: Instalar npm
        run: npm install
      - name: Instalar dependências
        run: npm ci
      - name: Instalar Jest
        run: npm install --save-dev jest supertest
      - name: Execução dos testes unitários
        run: npm test

  # Test: 
  # runs-on: ubuntu-latest
  # steps: 
  #   - uses: actions/checkout@v3
  #   - name: Usar Node 18.x
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: '18.x'
  #   - name: Instalar dependencias
  #     run: npm install
  #   - name: Instalar dependencias
  #     run: npm ci
  #   - name: Instalar jest
  #     run: npm install --save-dev jest supertest
  #   - name: Rodar testes de unidade com Jest
  #     run: npm test

  # Installation:
  #   runs-on: ubuntu-latest
  #   name: Installation
  #   steps:
  #     - name: Configurar Node 14 usando action do catálogo do Marketplace
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: '14'
  #     - name: Mostrar versão do Node que foi configurada
  #       run: node --version
  #     - name: Instalar npm
  #       run: npm install
  #     - name: Instalar Jest
  #       run: npm install --save-dev jest supertest

  # Checkout:
  #   runs-on: ubuntu-latest
  #   needs: Installation
  #   name: Checkout    
  #   steps:
  #     - name: Fazer o checkout usando action do catálogo do Marketplace
  #       uses: actions/checkout@v2
  #       with:
  #         path: ./

  # Execute: 
  #   runs-on: ubuntu-latest
  #   needs: Deploy-on-Cloud
  #   name: Execute
  #   steps:
  #     - name: Execução da aplicação
  #       run: npm start