name: TaProntos

on:
  push:
    branches: [ "main" ]
    
jobs:
  Installation:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Node 14 usando action do catálogo do Marketplace
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Mostrar versão do Node que foi configurada
        run: node --version

  Checkout:
    runs-on: ubuntu-latest
    needs: Installation
    name: Realizar o checkout no repositório GIT    
    steps:
      - name: Fazer o checkout usando action do catálogo do Marketplace
        uses: actions/checkout@v2

  Run: 
    runs-on: ubuntu-latest
    needs: Checkout
    name: Disparar build
    steps:
      - name: Execução da aplicação
        run: npm run build

  Tests: 
    runs-on: ubuntu-latest
    name: Disparar testes
    steps: 
      - name: Execução dos testes unitários
        run: |
          npm install --save-dev jest supertest
          npm test
