name: taprontos-pipeline

on:
  push:
    branches: [ "main" ]
    
jobs:
  exibir_mensagem_no_console:
    runs-on: ubuntu-latest
    steps:
      - name: Executa comando para exibir mensagem
        run: echo "Job da Pipeline disparado com sucesso"

  instalar_node:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Node 14 usando action do catálogo do Marketplace
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Mostrar versão do Node que foi configurada
        run: node --version

  fazer_checkout_do_repositorio:
    runs-on: ubuntu-latest
    needs: instalar_node
    name: Ação que faz o checkout no repositório GIT    
    steps:
      - name: Fazer o checkout usando action do catálogo do Marketplace
        uses: actions/checkout@v2
      - name: Exibir um Hello World no console
        run: echo "Hello, world!"
