name: TaProntos

on:
  push:
    branches: [ "main" ]
    
jobs:
  Installation:
    runs-on: ubuntu-latest
    name: Installation
    steps:
      - name: Configurar Node 20 usando action do catálogo do Marketplace
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Mostrar versão do Node que foi configurada
        run: node --version
      - name: Instalar npm
        run: npm install
      - name: Instalar Jest
        run: npm install --save-dev jest supertest

  Checkout:
    runs-on: ubuntu-latest
    needs: Installation
    name: Checkout    
    steps:
      - name: Fazer o checkout usando action do catálogo do Marketplace
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          path: ../
          working-directory: ../

  Build:
    runs-on: ubuntu-latest
    needs: Checkout
    steps:
      - name: Instalar dependências
        run: npm ci
      - name: Rodar script 'build' se ele existir no package-json
        run: npm run build --if-present

  Deploy-on-Cloud:
    runs-on: ubuntu-latest
    needs: Build
    name: Deploy on Cloud
    steps:
      - name: Fazer o Deploy do código no servidor hospedado em nuvem na plataforma Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}

  Execute: 
    runs-on: ubuntu-latest
    needs: Deploy-on-Cloud
    name: Execute
    steps:
      - name: Execução da aplicação
        run: npm start
        
  Test: 
    runs-on: ubuntu-latest
    needs: Execute
    name: Test
    steps: 
      - name: Execução dos testes unitários
        run: npm test
