name: TaProntos

on:
  push:
    branches: [ "main" ]
    
jobs:
  Installation:
    runs-on: ubuntu-latest
    name: Installation
    steps:
      - name: Configurar Node 14 usando action do catálogo do Marketplace
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Mostrar versão do Node que foi configurada
        run: node --version
      - name: Instalar npm
        run: npm install
      - name: Instalar Jest
        run: npm install --save-dev jest supertest

  Checkout:
    runs-on: ubuntu-latest
    needs: Installation
    name: Checkout    
    steps:
      - name: Fazer o checkout usando action do catálogo do Marketplace
        uses: actions/checkout@v2
        with:
          path: ./

  Deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.4        
        with:
          service_id: cpdlvrfsc6pc739415n0
          api_key: ''

  Execute: 
    runs-on: ubuntu-latest
    needs: Checkout
    name: Execute
    steps:
      - name: Execução da aplicação
        run: npm start
        
  Test: 
    runs-on: ubuntu-latest
    needs: Execute
    name: Test
    steps: 
      - name: Execução dos testes unitários
        run: npm test
